export type ProductCategory = {
  id: string;
  slug: string;
  name: string;
  description: string;
};

export type Product = {
  id: string;
  categoryId: string;
  name: string;
  description: string;
  price: number;
  compareAtPrice?: number;
  currency: "USD";
  sku: string;
  stock: number;
  rating: number;
  reviewCount: number;
  colors: string[];
  tags: string[];
  heroImage: string;
  gallery: string[];
};

export const productCategories: ProductCategory[] = [
  {
    id: "cat_apparel",
    slug: "apparel",
    name: "Apparel",
    description: "Everyday wardrobe staples with clean materials and seasonal colors."
  },
  {
    id: "cat_home",
    slug: "home",
    name: "Home",
    description: "Soft goods, tabletop pieces, lighting, and small home upgrades."
  },
  {
    id: "cat_electronics",
    slug: "electronics",
    name: "Electronics",
    description: "Portable devices, desk gear, and audio accessories for daily use."
  },
  {
    id: "cat_wellness",
    slug: "wellness",
    name: "Wellness",
    description: "Recovery, hydration, skincare, and personal care essentials."
  },
  {
    id: "cat_outdoor",
    slug: "outdoor",
    name: "Outdoor",
    description: "Trail, picnic, travel, and weather-ready equipment."
  },
  {
    id: "cat_accessories",
    slug: "accessories",
    name: "Accessories",
    description: "Bags, organizers, travel pieces, and small everyday carry goods."
  }
];

export const products: Product[] = [
  {
    id: "prod_linen_overshirt_01",
    categoryId: "cat_apparel",
    name: "Linen utility overshirt",
    description: "A breathable midweight overshirt with corozo-style buttons and two low-profile chest pockets.",
    price: 88,
    currency: "USD",
    sku: "APP-LIN-OSH-01",
    stock: 42,
    rating: 4.7,
    reviewCount: 186,
    colors: ["sage", "ivory", "navy"],
    tags: ["linen", "layering", "spring"],
    heroImage: "/assets/ecommerce/apparel.jpg",
    gallery: ["/assets/ecommerce/apparel.jpg", "/assets/ecommerce/apparel.jpg"]
  },
  {
    id: "prod_merino_travel_tee_01",
    categoryId: "cat_apparel",
    name: "Merino travel tee",
    description: "Odor-resistant merino blend tee cut for daily wear and compact packing.",
    price: 64,
    currency: "USD",
    sku: "APP-MER-TEE-01",
    stock: 70,
    rating: 4.8,
    reviewCount: 241,
    colors: ["charcoal", "heather gray", "sea blue"],
    tags: ["travel", "merino", "basics"],
    heroImage: "/assets/ecommerce/apparel.jpg",
    gallery: ["/assets/ecommerce/apparel.jpg", "/assets/ecommerce/apparel.jpg"]
  },
  {
    id: "prod_canvas_chore_jacket_01",
    categoryId: "cat_apparel",
    name: "Canvas chore jacket",
    description: "Washed cotton canvas jacket with reinforced elbows and roomy patch pockets.",
    price: 128,
    compareAtPrice: 148,
    currency: "USD",
    sku: "APP-CAN-JKT-01",
    stock: 18,
    rating: 4.6,
    reviewCount: 97,
    colors: ["clay", "moss", "black"],
    tags: ["outerwear", "canvas", "workwear"],
    heroImage: "/assets/ecommerce/apparel.jpg",
    gallery: ["/assets/ecommerce/apparel.jpg", "/assets/ecommerce/apparel.jpg"]
  },
  {
    id: "prod_stretch_commuter_pant_01",
    categoryId: "cat_apparel",
    name: "Stretch commuter pant",
    description: "Tapered stretch pant with hidden zip pockets and a water-repellent finish.",
    price: 96,
    currency: "USD",
    sku: "APP-STR-PNT-01",
    stock: 55,
    rating: 4.5,
    reviewCount: 132,
    colors: ["black", "olive", "stone"],
    tags: ["commute", "stretch", "travel"],
    heroImage: "/assets/ecommerce/apparel.jpg",
    gallery: ["/assets/ecommerce/apparel.jpg", "/assets/ecommerce/apparel.jpg"]
  },
  {
    id: "prod_quilted_house_slipper_01",
    categoryId: "cat_apparel",
    name: "Quilted house slipper",
    description: "Soft quilted indoor slipper with recycled fleece lining and a flexible rubber sole.",
    price: 54,
    currency: "USD",
    sku: "APP-QUI-SLP-01",
    stock: 34,
    rating: 4.9,
    reviewCount: 204,
    colors: ["oat", "graphite", "plum"],
    tags: ["loungewear", "fleece", "comfort"],
    heroImage: "/assets/ecommerce/apparel.jpg",
    gallery: ["/assets/ecommerce/apparel.jpg", "/assets/ecommerce/apparel.jpg"]
  },
  {
    id: "prod_ceramic_table_lamp_01",
    categoryId: "cat_home",
    name: "Ceramic table lamp",
    description: "Textured ceramic lamp with linen shade and inline dimmer for warm ambient light.",
    price: 142,
    currency: "USD",
    sku: "HOM-CER-LMP-01",
    stock: 21,
    rating: 4.7,
    reviewCount: 88,
    colors: ["cream", "terracotta"],
    tags: ["lighting", "ceramic", "bedroom"],
    heroImage: "/assets/ecommerce/home.jpg",
    gallery: ["/assets/ecommerce/home.jpg", "/assets/ecommerce/home.jpg"]
  },
  {
    id: "prod_waffle_throw_blanket_01",
    categoryId: "cat_home",
    name: "Waffle throw blanket",
    description: "Oversized cotton waffle throw with a soft garment-washed hand feel.",
    price: 74,
    currency: "USD",
    sku: "HOM-WAF-THR-01",
    stock: 64,
    rating: 4.8,
    reviewCount: 173,
    colors: ["natural", "indigo", "rust"],
    tags: ["textiles", "cotton", "living room"],
    heroImage: "/assets/ecommerce/home.jpg",
    gallery: ["/assets/ecommerce/home.jpg", "/assets/ecommerce/home.jpg"]
  },
  {
    id: "prod_stackable_dinnerware_01",
    categoryId: "cat_home",
    name: "Stackable dinnerware set",
    description: "Matte stoneware dinnerware set for four with compact nesting bowls and plates.",
    price: 118,
    currency: "USD",
    sku: "HOM-STO-DIN-01",
    stock: 27,
    rating: 4.6,
    reviewCount: 119,
    colors: ["speckle white", "charcoal", "sage"],
    tags: ["kitchen", "stoneware", "tabletop"],
    heroImage: "/assets/ecommerce/home.jpg",
    gallery: ["/assets/ecommerce/home.jpg", "/assets/ecommerce/home.jpg"]
  },
  {
    id: "prod_modular_wall_shelf_01",
    categoryId: "cat_home",
    name: "Modular wall shelf",
    description: "Oak-finished modular shelf with movable bookends and concealed mounting hardware.",
    price: 156,
    currency: "USD",
    sku: "HOM-MOD-SHF-01",
    stock: 16,
    rating: 4.4,
    reviewCount: 73,
    colors: ["oak", "walnut", "black"],
    tags: ["storage", "wood", "entryway"],
    heroImage: "/assets/ecommerce/home.jpg",
    gallery: ["/assets/ecommerce/home.jpg", "/assets/ecommerce/home.jpg"]
  },
  {
    id: "prod_scented_soy_candle_01",
    categoryId: "cat_home",
    name: "Scented soy candle trio",
    description: "Three clean-burning soy candles with cedar citrus, rain fig, and amber tea scents.",
    price: 48,
    currency: "USD",
    sku: "HOM-SOY-CAN-01",
    stock: 83,
    rating: 4.9,
    reviewCount: 314,
    colors: ["amber", "smoke", "white"],
    tags: ["candle", "gift", "fragrance"],
    heroImage: "/assets/ecommerce/home.jpg",
    gallery: ["/assets/ecommerce/home.jpg", "/assets/ecommerce/home.jpg"]
  },
  {
    id: "prod_noise_canceling_earbuds_01",
    categoryId: "cat_electronics",
    name: "Noise-canceling earbuds",
    description: "Compact wireless earbuds with adaptive noise cancellation and a 30-hour charging case.",
    price: 149,
    compareAtPrice: 179,
    currency: "USD",
    sku: "ELC-NCE-EBD-01",
    stock: 39,
    rating: 4.7,
    reviewCount: 422,
    colors: ["matte black", "porcelain", "sage"],
    tags: ["audio", "wireless", "travel"],
    heroImage: "/assets/ecommerce/electronics.jpg",
    gallery: ["/assets/ecommerce/electronics.jpg", "/assets/ecommerce/electronics.jpg"]
  },
  {
    id: "prod_portable_mini_projector_01",
    categoryId: "cat_electronics",
    name: "Portable mini projector",
    description: "Palm-sized 1080p projector with auto keystone, HDMI, USB-C, and built-in speaker.",
    price: 289,
    currency: "USD",
    sku: "ELC-MIN-PRJ-01",
    stock: 11,
    rating: 4.5,
    reviewCount: 66,
    colors: ["graphite"],
    tags: ["projector", "movie night", "portable"],
    heroImage: "/assets/ecommerce/electronics.jpg",
    gallery: ["/assets/ecommerce/electronics.jpg", "/assets/ecommerce/electronics.jpg"]
  },
  {
    id: "prod_usb_c_desk_hub_01",
    categoryId: "cat_electronics",
    name: "USB-C desk hub",
    description: "Aluminum desk hub with HDMI, Ethernet, SD reader, and 100W pass-through charging.",
    price: 92,
    currency: "USD",
    sku: "ELC-USC-HUB-01",
    stock: 58,
    rating: 4.6,
    reviewCount: 155,
    colors: ["silver", "space gray"],
    tags: ["desk", "usb-c", "productivity"],
    heroImage: "/assets/ecommerce/electronics.jpg",
    gallery: ["/assets/ecommerce/electronics.jpg", "/assets/ecommerce/electronics.jpg"]
  },
  {
    id: "prod_smart_alarm_clock_01",
    categoryId: "cat_electronics",
    name: "Smart sunrise alarm clock",
    description: "Sunrise alarm with dimmable display, white noise, Bluetooth speaker, and app-free controls.",
    price: 84,
    currency: "USD",
    sku: "ELC-SUN-CLK-01",
    stock: 46,
    rating: 4.4,
    reviewCount: 137,
    colors: ["white", "sand"],
    tags: ["sleep", "bedside", "speaker"],
    heroImage: "/assets/ecommerce/electronics.jpg",
    gallery: ["/assets/ecommerce/electronics.jpg", "/assets/ecommerce/electronics.jpg"]
  },
  {
    id: "prod_wireless_charging_tray_01",
    categoryId: "cat_electronics",
    name: "Wireless charging tray",
    description: "Vegan leather catchall tray with dual wireless charging pads and cable management.",
    price: 76,
    currency: "USD",
    sku: "ELC-WCH-TRY-01",
    stock: 25,
    rating: 4.5,
    reviewCount: 102,
    colors: ["black", "camel"],
    tags: ["charging", "entryway", "organization"],
    heroImage: "/assets/ecommerce/electronics.jpg",
    gallery: ["/assets/ecommerce/electronics.jpg", "/assets/ecommerce/electronics.jpg"]
  },
  {
    id: "prod_stainless_water_bottle_01",
    categoryId: "cat_wellness",
    name: "Insulated water bottle",
    description: "Leakproof stainless steel bottle with ceramic lining and a carry loop lid.",
    price: 38,
    currency: "USD",
    sku: "WEL-INS-BOT-01",
    stock: 96,
    rating: 4.9,
    reviewCount: 518,
    colors: ["pine", "clay", "ice"],
    tags: ["hydration", "stainless steel", "daily carry"],
    heroImage: "/assets/ecommerce/wellness.jpg",
    gallery: ["/assets/ecommerce/wellness.jpg", "/assets/ecommerce/wellness.jpg"]
  },
  {
    id: "prod_weighted_eye_mask_01",
    categoryId: "cat_wellness",
    name: "Weighted silk eye mask",
    description: "Cooling silk eye mask with removable glass-bead insert and adjustable strap.",
    price: 44,
    currency: "USD",
    sku: "WEL-WGT-MSK-01",
    stock: 37,
    rating: 4.6,
    reviewCount: 89,
    colors: ["midnight", "rose", "champagne"],
    tags: ["sleep", "silk", "travel"],
    heroImage: "/assets/ecommerce/wellness.jpg",
    gallery: ["/assets/ecommerce/wellness.jpg", "/assets/ecommerce/wellness.jpg"]
  },
  {
    id: "prod_recovery_foam_roller_01",
    categoryId: "cat_wellness",
    name: "Textured foam roller",
    description: "Firm EVA foam roller with multi-zone texture for post-workout recovery.",
    price: 36,
    currency: "USD",
    sku: "WEL-FOM-ROL-01",
    stock: 44,
    rating: 4.5,
    reviewCount: 113,
    colors: ["charcoal", "blue"],
    tags: ["fitness", "recovery", "mobility"],
    heroImage: "/assets/ecommerce/wellness.jpg",
    gallery: ["/assets/ecommerce/wellness.jpg", "/assets/ecommerce/wellness.jpg"]
  },
  {
    id: "prod_mineral_sunscreen_01",
    categoryId: "cat_wellness",
    name: "Mineral sunscreen SPF 40",
    description: "Fragrance-free mineral sunscreen with a sheer finish and reef-conscious formula.",
    price: 28,
    currency: "USD",
    sku: "WEL-MIN-SPF-01",
    stock: 120,
    rating: 4.7,
    reviewCount: 263,
    colors: ["white"],
    tags: ["skincare", "spf", "travel size"],
    heroImage: "/assets/ecommerce/wellness.jpg",
    gallery: ["/assets/ecommerce/wellness.jpg", "/assets/ecommerce/wellness.jpg"]
  },
  {
    id: "prod_aromatherapy_diffuser_01",
    categoryId: "cat_wellness",
    name: "Ceramic aromatherapy diffuser",
    description: "Quiet ultrasonic diffuser with ceramic cover and warm dimmable light.",
    price: 68,
    currency: "USD",
    sku: "WEL-ARO-DIF-01",
    stock: 29,
    rating: 4.4,
    reviewCount: 76,
    colors: ["stone", "sage"],
    tags: ["aromatherapy", "ceramic", "relaxation"],
    heroImage: "/assets/ecommerce/wellness.jpg",
    gallery: ["/assets/ecommerce/wellness.jpg", "/assets/ecommerce/wellness.jpg"]
  },
  {
    id: "prod_packable_rain_shell_01",
    categoryId: "cat_outdoor",
    name: "Packable rain shell",
    description: "Lightweight waterproof shell that packs into its own pocket for trail or city use.",
    price: 118,
    currency: "USD",
    sku: "OUT-RAN-SHL-01",
    stock: 33,
    rating: 4.8,
    reviewCount: 164,
    colors: ["alpine blue", "black", "cypress"],
    tags: ["rainwear", "hiking", "packable"],
    heroImage: "/assets/ecommerce/outdoor.jpg",
    gallery: ["/assets/ecommerce/outdoor.jpg", "/assets/ecommerce/outdoor.jpg"]
  },
  {
    id: "prod_trail_daypack_01",
    categoryId: "cat_outdoor",
    name: "Trail daypack 24L",
    description: "Ventilated 24-liter daypack with hydration sleeve, rain cover, and trekking pole loops.",
    price: 132,
    currency: "USD",
    sku: "OUT-TRL-PCK-01",
    stock: 24,
    rating: 4.6,
    reviewCount: 91,
    colors: ["forest", "slate", "ember"],
    tags: ["backpack", "hiking", "hydration"],
    heroImage: "/assets/ecommerce/outdoor.jpg",
    gallery: ["/assets/ecommerce/outdoor.jpg", "/assets/ecommerce/outdoor.jpg"]
  },
  {
    id: "prod_enamel_picnic_set_01",
    categoryId: "cat_outdoor",
    name: "Enamel picnic set",
    description: "Durable enamel picnic set with four plates, bowls, mugs, and a roll-top storage bag.",
    price: 86,
    currency: "USD",
    sku: "OUT-ENA-PIC-01",
    stock: 19,
    rating: 4.5,
    reviewCount: 57,
    colors: ["cream", "navy"],
    tags: ["camp", "picnic", "tableware"],
    heroImage: "/assets/ecommerce/outdoor.jpg",
    gallery: ["/assets/ecommerce/outdoor.jpg", "/assets/ecommerce/outdoor.jpg"]
  },
  {
    id: "prod_compact_camp_chair_01",
    categoryId: "cat_outdoor",
    name: "Compact camp chair",
    description: "Low-profile folding chair with aluminum frame, ripstop seat, and shoulder carry bag.",
    price: 72,
    currency: "USD",
    sku: "OUT-CMP-CHR-01",
    stock: 40,
    rating: 4.7,
    reviewCount: 138,
    colors: ["sand", "green", "black"],
    tags: ["camping", "chair", "portable"],
    heroImage: "/assets/ecommerce/outdoor.jpg",
    gallery: ["/assets/ecommerce/outdoor.jpg", "/assets/ecommerce/outdoor.jpg"]
  },
  {
    id: "prod_thermal_travel_mug_01",
    categoryId: "cat_outdoor",
    name: "Thermal travel mug",
    description: "Cupholder-friendly insulated mug with ceramic coating and a spill-resistant slider lid.",
    price: 34,
    currency: "USD",
    sku: "OUT-THR-MUG-01",
    stock: 87,
    rating: 4.8,
    reviewCount: 295,
    colors: ["black", "canyon", "seafoam"],
    tags: ["coffee", "travel", "insulated"],
    heroImage: "/assets/ecommerce/outdoor.jpg",
    gallery: ["/assets/ecommerce/outdoor.jpg", "/assets/ecommerce/outdoor.jpg"]
  },
  {
    id: "prod_weekender_duffel_01",
    categoryId: "cat_accessories",
    name: "Waxed canvas weekender",
    description: "Carry-on sized waxed canvas duffel with shoe pocket and recycled nylon lining.",
    price: 168,
    currency: "USD",
    sku: "ACC-WAX-DUF-01",
    stock: 22,
    rating: 4.7,
    reviewCount: 111,
    colors: ["olive", "tan", "black"],
    tags: ["travel", "duffel", "canvas"],
    heroImage: "/assets/ecommerce/accessories.jpg",
    gallery: ["/assets/ecommerce/accessories.jpg", "/assets/ecommerce/accessories.jpg"]
  },
  {
    id: "prod_tech_organizer_pouch_01",
    categoryId: "cat_accessories",
    name: "Tech organizer pouch",
    description: "Structured zip pouch with elastic loops, mesh pockets, and padded tablet cable sleeve.",
    price: 46,
    currency: "USD",
    sku: "ACC-TCH-ORG-01",
    stock: 61,
    rating: 4.6,
    reviewCount: 149,
    colors: ["charcoal", "cobalt", "moss"],
    tags: ["organization", "travel", "desk"],
    heroImage: "/assets/ecommerce/accessories.jpg",
    gallery: ["/assets/ecommerce/accessories.jpg", "/assets/ecommerce/accessories.jpg"]
  },
  {
    id: "prod_leather_card_wallet_01",
    categoryId: "cat_accessories",
    name: "Slim leather card wallet",
    description: "Minimal leather card wallet with six card slots and a central cash pocket.",
    price: 58,
    currency: "USD",
    sku: "ACC-LTH-WAL-01",
    stock: 49,
    rating: 4.8,
    reviewCount: 232,
    colors: ["cognac", "black", "forest"],
    tags: ["wallet", "leather", "everyday carry"],
    heroImage: "/assets/ecommerce/accessories.jpg",
    gallery: ["/assets/ecommerce/accessories.jpg", "/assets/ecommerce/accessories.jpg"]
  },
  {
    id: "prod_recycled_tote_01",
    categoryId: "cat_accessories",
    name: "Recycled market tote",
    description: "Structured recycled-cotton tote with snap closure, inner bottle loop, and laptop sleeve.",
    price: 42,
    currency: "USD",
    sku: "ACC-REC-TOT-01",
    stock: 75,
    rating: 4.5,
    reviewCount: 84,
    colors: ["natural", "black", "coral"],
    tags: ["tote", "market", "recycled"],
    heroImage: "/assets/ecommerce/accessories.jpg",
    gallery: ["/assets/ecommerce/accessories.jpg", "/assets/ecommerce/accessories.jpg"]
  },
  {
    id: "prod_travel_jewelry_case_01",
    categoryId: "cat_accessories",
    name: "Travel jewelry case",
    description: "Compact velvet-lined jewelry case with ring bar, necklace hooks, and removable dividers.",
    price: 52,
    currency: "USD",
    sku: "ACC-JWL-CSE-01",
    stock: 28,
    rating: 4.6,
    reviewCount: 68,
    colors: ["blush", "navy", "cream"],
    tags: ["travel", "jewelry", "gift"],
    heroImage: "/assets/ecommerce/accessories.jpg",
    gallery: ["/assets/ecommerce/accessories.jpg", "/assets/ecommerce/accessories.jpg"]
  }
];
