export type CarFuelType = "gasoline" | "hybrid" | "plug-in-hybrid" | "electric" | "diesel";
export type CarCondition = "new" | "used" | "certified";
export type CarBodyStyle = "sedan" | "suv" | "truck" | "coupe" | "hatchback" | "wagon" | "van";

export type CarDealer = {
  id: string;
  name: string;
  city: string;
  state: string;
  address: string;
  phone: string;
  rating: number;
  services: string[];
};

export type CarListing = {
  id: string;
  dealerId: string;
  make: string;
  model: string;
  trim: string;
  year: number;
  price: number;
  mileage: number;
  fuelType: CarFuelType;
  transmission: "automatic" | "manual";
  city: string;
  state: string;
  condition: CarCondition;
  bodyStyle: CarBodyStyle;
  exteriorColor: string;
  interiorColor: string;
  drivetrain: "FWD" | "RWD" | "AWD" | "4WD";
  rangeMiles?: number;
  mpgCity?: number;
  mpgHighway?: number;
  heroImage: string;
  gallery: string[];
  features: string[];
};

export const carDealers: CarDealer[] = [
  {
    id: "dealer_austin_modern_motors",
    name: "Modern Motors Austin",
    city: "Austin",
    state: "TX",
    address: "4812 S Congress Ave",
    phone: "+1-512-555-0148",
    rating: 4.8,
    services: ["financing", "delivery", "service center"]
  },
  {
    id: "dealer_seattle_greenline",
    name: "Greenline Auto Seattle",
    city: "Seattle",
    state: "WA",
    address: "224 Elliott Ave W",
    phone: "+1-206-555-0191",
    rating: 4.9,
    services: ["EV specialists", "home charger setup", "delivery"]
  },
  {
    id: "dealer_denver_peak",
    name: "Peak Drive Denver",
    city: "Denver",
    state: "CO",
    address: "3180 Brighton Blvd",
    phone: "+1-303-555-0136",
    rating: 4.7,
    services: ["trade-ins", "winter packages", "service center"]
  },
  {
    id: "dealer_chicago_loop",
    name: "Loop City Cars",
    city: "Chicago",
    state: "IL",
    address: "905 W Randolph St",
    phone: "+1-312-555-0167",
    rating: 4.6,
    services: ["certified pre-owned", "pickup", "financing"]
  },
  {
    id: "dealer_miami_bayfront",
    name: "Bayfront Auto Miami",
    city: "Miami",
    state: "FL",
    address: "1740 Biscayne Blvd",
    phone: "+1-305-555-0182",
    rating: 4.8,
    services: ["delivery", "lease returns", "detailing"]
  },
  {
    id: "dealer_portland_river",
    name: "Riverline Motors Portland",
    city: "Portland",
    state: "OR",
    address: "288 NW 13th Ave",
    phone: "+1-503-555-0119",
    rating: 4.7,
    services: ["hybrid specialists", "service center", "financing"]
  }
];

export const carListings: CarListing[] = [
  {
    id: "car_aster_sedan_01",
    dealerId: "dealer_austin_modern_motors",
    make: "Aster",
    model: "Vale",
    trim: "LX",
    year: 2025,
    price: 42800,
    mileage: 820,
    fuelType: "hybrid",
    transmission: "automatic",
    city: "Austin",
    state: "TX",
    condition: "certified",
    bodyStyle: "sedan",
    exteriorColor: "Graphite Blue",
    interiorColor: "Stone",
    drivetrain: "FWD",
    mpgCity: 48,
    mpgHighway: 44,
    heroImage: "/assets/cars/aster-vale-hero.svg",
    gallery: ["/assets/cars/aster-vale-interior.svg", "/assets/cars/aster-vale-rear.svg"],
    features: ["Adaptive cruise", "Panoramic roof", "Lane assist", "Ventilated seats"]
  },
  {
    id: "car_electra_suv_01",
    dealerId: "dealer_seattle_greenline",
    make: "Electra",
    model: "Northstar",
    trim: "Touring AWD",
    year: 2026,
    price: 61200,
    mileage: 120,
    fuelType: "electric",
    transmission: "automatic",
    city: "Seattle",
    state: "WA",
    condition: "new",
    bodyStyle: "suv",
    exteriorColor: "Glacier White",
    interiorColor: "Charcoal",
    drivetrain: "AWD",
    rangeMiles: 420,
    heroImage: "/assets/cars/electra-northstar-hero.svg",
    gallery: ["/assets/cars/electra-northstar-interior.svg", "/assets/cars/electra-northstar-rear.svg"],
    features: ["420 mile range", "Fast charge", "All-wheel drive", "Glass roof"]
  },
  {
    id: "car_metro_hatch_01",
    dealerId: "dealer_denver_peak",
    make: "Metro",
    model: "Pulse",
    trim: "Select",
    year: 2023,
    price: 18400,
    mileage: 21450,
    fuelType: "gasoline",
    transmission: "automatic",
    city: "Denver",
    state: "CO",
    condition: "used",
    bodyStyle: "hatchback",
    exteriorColor: "Signal Red",
    interiorColor: "Black",
    drivetrain: "FWD",
    mpgCity: 31,
    mpgHighway: 39,
    heroImage: "/assets/cars/metro-pulse-hero.svg",
    gallery: ["/assets/cars/metro-pulse-interior.svg", "/assets/cars/metro-pulse-rear.svg"],
    features: ["Backup camera", "Wireless CarPlay", "Heated seats", "Blind spot monitor"]
  },
  {
    id: "car_velo_coupe_01",
    dealerId: "dealer_miami_bayfront",
    make: "Velo",
    model: "Aria",
    trim: "GT",
    year: 2025,
    price: 52900,
    mileage: 3400,
    fuelType: "gasoline",
    transmission: "manual",
    city: "Miami",
    state: "FL",
    condition: "certified",
    bodyStyle: "coupe",
    exteriorColor: "Solar Yellow",
    interiorColor: "Ebony",
    drivetrain: "RWD",
    mpgCity: 22,
    mpgHighway: 31,
    heroImage: "/assets/cars/velo-aria-hero.svg",
    gallery: ["/assets/cars/velo-aria-interior.svg", "/assets/cars/velo-aria-rear.svg"],
    features: ["Sport exhaust", "Limited-slip differential", "Performance seats", "Brembo-style brakes"]
  },
  {
    id: "car_orion_wagon_01",
    dealerId: "dealer_portland_river",
    make: "Orion",
    model: "Meadow",
    trim: "Cross",
    year: 2024,
    price: 37650,
    mileage: 8950,
    fuelType: "plug-in-hybrid",
    transmission: "automatic",
    city: "Portland",
    state: "OR",
    condition: "certified",
    bodyStyle: "wagon",
    exteriorColor: "Pine Green",
    interiorColor: "Warm Gray",
    drivetrain: "AWD",
    rangeMiles: 38,
    mpgCity: 52,
    mpgHighway: 47,
    heroImage: "/assets/cars/orion-meadow-hero.svg",
    gallery: ["/assets/cars/orion-meadow-interior.svg", "/assets/cars/orion-meadow-rear.svg"],
    features: ["Plug-in hybrid range", "Roof rails", "Heated steering wheel", "Cargo organizer"]
  },
  {
    id: "car_nova_truck_01",
    dealerId: "dealer_denver_peak",
    make: "Nova",
    model: "Ridge",
    trim: "Trail 4WD",
    year: 2025,
    price: 48700,
    mileage: 620,
    fuelType: "diesel",
    transmission: "automatic",
    city: "Denver",
    state: "CO",
    condition: "new",
    bodyStyle: "truck",
    exteriorColor: "Basalt Gray",
    interiorColor: "Graphite",
    drivetrain: "4WD",
    mpgCity: 24,
    mpgHighway: 29,
    heroImage: "/assets/cars/nova-ridge-hero.svg",
    gallery: ["/assets/cars/nova-ridge-interior.svg", "/assets/cars/nova-ridge-rear.svg"],
    features: ["Tow package", "Spray-in bedliner", "360 camera", "Locking rear differential"]
  },
  {
    id: "car_luma_suv_01",
    dealerId: "dealer_chicago_loop",
    make: "Luma",
    model: "Harbor",
    trim: "Premium",
    year: 2024,
    price: 35450,
    mileage: 11200,
    fuelType: "hybrid",
    transmission: "automatic",
    city: "Chicago",
    state: "IL",
    condition: "certified",
    bodyStyle: "suv",
    exteriorColor: "Midnight Teal",
    interiorColor: "Saddle",
    drivetrain: "AWD",
    mpgCity: 41,
    mpgHighway: 38,
    heroImage: "/assets/cars/luma-harbor-hero.svg",
    gallery: ["/assets/cars/luma-harbor-interior.svg", "/assets/cars/luma-harbor-rear.svg"],
    features: ["Third-row seating", "Hands-free liftgate", "Navigation", "Heated second row"]
  },
  {
    id: "car_zenith_sedan_01",
    dealerId: "dealer_austin_modern_motors",
    make: "Zenith",
    model: "Crest",
    trim: "Signature",
    year: 2026,
    price: 68900,
    mileage: 90,
    fuelType: "electric",
    transmission: "automatic",
    city: "Austin",
    state: "TX",
    condition: "new",
    bodyStyle: "sedan",
    exteriorColor: "Pearl Silver",
    interiorColor: "Navy",
    drivetrain: "AWD",
    rangeMiles: 386,
    heroImage: "/assets/cars/zenith-crest-hero.svg",
    gallery: ["/assets/cars/zenith-crest-interior.svg", "/assets/cars/zenith-crest-rear.svg"],
    features: ["Adaptive air suspension", "Executive rear seating", "Bidirectional charging", "HUD"]
  },
  {
    id: "car_terra_van_01",
    dealerId: "dealer_portland_river",
    make: "Terra",
    model: "Wayfarer",
    trim: "Family",
    year: 2024,
    price: 39700,
    mileage: 7200,
    fuelType: "hybrid",
    transmission: "automatic",
    city: "Portland",
    state: "OR",
    condition: "used",
    bodyStyle: "van",
    exteriorColor: "Cloud White",
    interiorColor: "Charcoal",
    drivetrain: "FWD",
    mpgCity: 36,
    mpgHighway: 34,
    heroImage: "/assets/cars/terra-wayfarer-hero.svg",
    gallery: ["/assets/cars/terra-wayfarer-interior.svg", "/assets/cars/terra-wayfarer-rear.svg"],
    features: ["Power sliding doors", "Rear entertainment", "Stow-flat seats", "Adaptive cruise"]
  },
  {
    id: "car_halo_hatch_01",
    dealerId: "dealer_seattle_greenline",
    make: "Halo",
    model: "City",
    trim: "EV",
    year: 2025,
    price: 29950,
    mileage: 1400,
    fuelType: "electric",
    transmission: "automatic",
    city: "Seattle",
    state: "WA",
    condition: "certified",
    bodyStyle: "hatchback",
    exteriorColor: "Ice Mint",
    interiorColor: "Slate",
    drivetrain: "FWD",
    rangeMiles: 244,
    heroImage: "/assets/cars/halo-city-hero.svg",
    gallery: ["/assets/cars/halo-city-interior.svg", "/assets/cars/halo-city-rear.svg"],
    features: ["One-pedal drive", "Compact parking assist", "Heat pump", "Wireless charging"]
  },
  {
    id: "car_bristol_suv_01",
    dealerId: "dealer_chicago_loop",
    make: "Bristol",
    model: "Quarry",
    trim: "Reserve",
    year: 2022,
    price: 33400,
    mileage: 38600,
    fuelType: "gasoline",
    transmission: "automatic",
    city: "Chicago",
    state: "IL",
    condition: "used",
    bodyStyle: "suv",
    exteriorColor: "Deep Bronze",
    interiorColor: "Beige",
    drivetrain: "AWD",
    mpgCity: 21,
    mpgHighway: 28,
    heroImage: "/assets/cars/bristol-quarry-hero.svg",
    gallery: ["/assets/cars/bristol-quarry-interior.svg", "/assets/cars/bristol-quarry-rear.svg"],
    features: ["Leather seating", "Premium audio", "Tow hitch", "Tri-zone climate"]
  },
  {
    id: "car_cobalt_truck_01",
    dealerId: "dealer_austin_modern_motors",
    make: "Cobalt",
    model: "Range",
    trim: "Work Crew",
    year: 2023,
    price: 31900,
    mileage: 26450,
    fuelType: "gasoline",
    transmission: "automatic",
    city: "Austin",
    state: "TX",
    condition: "used",
    bodyStyle: "truck",
    exteriorColor: "Oxford White",
    interiorColor: "Gray",
    drivetrain: "4WD",
    mpgCity: 19,
    mpgHighway: 24,
    heroImage: "/assets/cars/cobalt-range-hero.svg",
    gallery: ["/assets/cars/cobalt-range-interior.svg", "/assets/cars/cobalt-range-rear.svg"],
    features: ["Crew cab", "Bed step", "Trailer brake controller", "All-terrain tires"]
  },
  {
    id: "car_solace_coupe_01",
    dealerId: "dealer_miami_bayfront",
    make: "Solace",
    model: "Eon",
    trim: "Sport",
    year: 2026,
    price: 44600,
    mileage: 40,
    fuelType: "electric",
    transmission: "automatic",
    city: "Miami",
    state: "FL",
    condition: "new",
    bodyStyle: "coupe",
    exteriorColor: "Liquid Silver",
    interiorColor: "Black",
    drivetrain: "RWD",
    rangeMiles: 305,
    heroImage: "/assets/cars/solace-eon-hero.svg",
    gallery: ["/assets/cars/solace-eon-interior.svg", "/assets/cars/solace-eon-rear.svg"],
    features: ["Performance mode", "Glass canopy", "Sport seats", "Fast charge"]
  },
  {
    id: "car_meridian_sedan_01",
    dealerId: "dealer_denver_peak",
    make: "Meridian",
    model: "Line",
    trim: "Touring",
    year: 2021,
    price: 23600,
    mileage: 42100,
    fuelType: "gasoline",
    transmission: "automatic",
    city: "Denver",
    state: "CO",
    condition: "used",
    bodyStyle: "sedan",
    exteriorColor: "Storm Gray",
    interiorColor: "Black",
    drivetrain: "FWD",
    mpgCity: 29,
    mpgHighway: 37,
    heroImage: "/assets/cars/meridian-line-hero.svg",
    gallery: ["/assets/cars/meridian-line-interior.svg", "/assets/cars/meridian-line-rear.svg"],
    features: ["Remote start", "Lane keeping", "Power driver seat", "Dual-zone climate"]
  },
  {
    id: "car_atlas_wagon_01",
    dealerId: "dealer_seattle_greenline",
    make: "Atlas",
    model: "Shore",
    trim: "Adventure",
    year: 2025,
    price: 46900,
    mileage: 260,
    fuelType: "plug-in-hybrid",
    transmission: "automatic",
    city: "Seattle",
    state: "WA",
    condition: "new",
    bodyStyle: "wagon",
    exteriorColor: "Harbor Blue",
    interiorColor: "Mist",
    drivetrain: "AWD",
    rangeMiles: 44,
    mpgCity: 50,
    mpgHighway: 46,
    heroImage: "/assets/cars/atlas-shore-hero.svg",
    gallery: ["/assets/cars/atlas-shore-interior.svg", "/assets/cars/atlas-shore-rear.svg"],
    features: ["Raised suspension", "Skid plates", "Panoramic roof", "Tow mode"]
  },
  {
    id: "car_prism_hatch_01",
    dealerId: "dealer_chicago_loop",
    make: "Prism",
    model: "Nimble",
    trim: "Urban",
    year: 2024,
    price: 22400,
    mileage: 12480,
    fuelType: "hybrid",
    transmission: "automatic",
    city: "Chicago",
    state: "IL",
    condition: "certified",
    bodyStyle: "hatchback",
    exteriorColor: "Copper",
    interiorColor: "Black",
    drivetrain: "FWD",
    mpgCity: 53,
    mpgHighway: 48,
    heroImage: "/assets/cars/prism-nimble-hero.svg",
    gallery: ["/assets/cars/prism-nimble-interior.svg", "/assets/cars/prism-nimble-rear.svg"],
    features: ["City safety suite", "Fold-flat rear seats", "Smart key", "Rain-sensing wipers"]
  },
  {
    id: "car_riven_suv_01",
    dealerId: "dealer_portland_river",
    make: "Riven",
    model: "Summit",
    trim: "Overland",
    year: 2025,
    price: 58300,
    mileage: 5100,
    fuelType: "diesel",
    transmission: "automatic",
    city: "Portland",
    state: "OR",
    condition: "certified",
    bodyStyle: "suv",
    exteriorColor: "Forest Green",
    interiorColor: "Tan",
    drivetrain: "4WD",
    mpgCity: 23,
    mpgHighway: 27,
    heroImage: "/assets/cars/riven-summit-hero.svg",
    gallery: ["/assets/cars/riven-summit-interior.svg", "/assets/cars/riven-summit-rear.svg"],
    features: ["Air suspension", "Terrain response", "Roof platform", "Underbody cameras"]
  },
  {
    id: "car_flux_van_01",
    dealerId: "dealer_miami_bayfront",
    make: "Flux",
    model: "Parcel",
    trim: "Cargo EV",
    year: 2026,
    price: 53200,
    mileage: 15,
    fuelType: "electric",
    transmission: "automatic",
    city: "Miami",
    state: "FL",
    condition: "new",
    bodyStyle: "van",
    exteriorColor: "Bright White",
    interiorColor: "Gray",
    drivetrain: "RWD",
    rangeMiles: 268,
    heroImage: "/assets/cars/flux-parcel-hero.svg",
    gallery: ["/assets/cars/flux-parcel-interior.svg", "/assets/cars/flux-parcel-rear.svg"],
    features: ["High roof", "Fleet telematics", "Sliding cargo door", "DC fast charging"]
  },
  {
    id: "car_sierra_sedan_01",
    dealerId: "dealer_austin_modern_motors",
    make: "Sierra",
    model: "Avenue",
    trim: "Limited",
    year: 2024,
    price: 31750,
    mileage: 15100,
    fuelType: "gasoline",
    transmission: "automatic",
    city: "Austin",
    state: "TX",
    condition: "certified",
    bodyStyle: "sedan",
    exteriorColor: "Champagne",
    interiorColor: "Espresso",
    drivetrain: "FWD",
    mpgCity: 28,
    mpgHighway: 36,
    heroImage: "/assets/cars/sierra-avenue-hero.svg",
    gallery: ["/assets/cars/sierra-avenue-interior.svg", "/assets/cars/sierra-avenue-rear.svg"],
    features: ["Premium audio", "Surround view", "Cooled seats", "Rear cross-traffic alert"]
  },
  {
    id: "car_aurora_suv_01",
    dealerId: "dealer_seattle_greenline",
    make: "Aurora",
    model: "Trail",
    trim: "Long Range",
    year: 2026,
    price: 64750,
    mileage: 55,
    fuelType: "electric",
    transmission: "automatic",
    city: "Seattle",
    state: "WA",
    condition: "new",
    bodyStyle: "suv",
    exteriorColor: "Arctic Blue",
    interiorColor: "Light Gray",
    drivetrain: "AWD",
    rangeMiles: 448,
    heroImage: "/assets/cars/aurora-trail-hero.svg",
    gallery: ["/assets/cars/aurora-trail-interior.svg", "/assets/cars/aurora-trail-rear.svg"],
    features: ["Long range battery", "Adaptive headlights", "Camp mode", "Tri-zone climate"]
  }
];
